version: 1
layer: awn-database-store

awn_schema:
  record:
    extends: awn.data.element.default
    fields:
      awn-code:
        type: awn.string
        title: Код (slug)
        required: true
      awn-label:
        type: awn.string
        title: Подпись
        required: true
      awn-sort:
        type: awn.integer
        title: Порядок
        default: 0
