version: 1
kind: singleton
id: editing-fields.field-def
name: Мета-схема поля
extends: ../../_base/configuration-schema.yml
description: awn.field.base — properties для описания полей в схемах

record:
  storage: md
  file: main.md

fields:
  title:
    type: awn.string
    title: Название
  fieldId:
    type: awn.string
    title: ID типа
    default: awn.field.base
  extends:
    type: awn.string
    title: Extends
    default: awn.entity
  status:
    type: awn.enum
    title: Статус
    enum: [active, inactive]
    default: active
