version: 1
layer: awn-data-store

awn_schema:
  record:
    extends: awn.data.element.default
    fields:
      awn-code:
        type: awn.string
        title: Код
        required: true
      awn-label:
        type: awn.string
        title: Подпись
        required: true
      awn-emoji:
        type: awn.string
        title: Эмодзи
      awn-color:
        type: awn.color
        title: Цвет
      awn-sort:
        type: awn.integer
        title: Порядок
        default: 0
