version: 1
layer: awn-database-store

awn_schema:
  frame:
    extends: awn.infoblock.frame.single
    fields:
      awn-field-1:
        type: awn.field.string
        name: ""
        placement: editor-body
        sort: 10
      awn-field-2:
        type: awn.field.string
        name: ""
        placement: editor-body
        sort: 20
  category:
    extends: awn.infoblock.element.category
    fields:
      awn-field-1:
        type: awn.field.string
        name: ""
        sort: 10
        placement: editor-body
      awn-field-2:
        type: awn.field.string
        name: ""
        sort: 20
        placement: editor-body
      awn-field-3:
        type: awn.field.string
        name: ""
        sort: 30
        placement: editor-body
  record:
    extends: awn.infoblock.element.record
    fields:
      awn-field-1:
        type: awn.field.string
        name: ""
        sort: 10
        placement: editor-body
      awn-field-2:
        type: awn.field.string
        name: ""
        sort: 20
        placement: editor-body
      awn-field-3:
        type: awn.field.string
        name: ""
        sort: 30
        placement: editor-body
      awn-field-4:
        type: awn.field.string
        name: ""
        sort: 40
        placement: editor-body
      awn-field-5:
        type: awn.field.string
        name: ""
        sort: 50
        placement: editor-body
  sidecar:
    extends: awn.infoblock.element.sidecar
    fields:
      awn-field-1:
        type: awn.field.string
        name: ""
        sort: 10
        placement: editor-body
      awn-field-2:
        type: awn.field.string
        name: ""
        sort: 20
        placement: editor-body
      awn-field-3:
        type: awn.field.string
        name: ""
        sort: 30
        placement: editor-body
      awn-field-4:
        type: awn.field.string
        name: ""
        sort: 40
        placement: editor-body
      awn-field-5:
        type: awn.field.string
        name: ""
        sort: 50
        placement: editor-body
      awn-field-6:
        type: awn.field.string
        name: ""
        sort: 60
        placement: editor-body
      awn-field-7:
        type: awn.field.string
        name: ""
        sort: 70
        placement: editor-body
      awn-field-8:
        type: awn.field.string
        name: ""
        sort: 80
        placement: editor-body
