version: 1
kind: collection
id: taxonomies.statuses
name: Статусы
extends: ../../_base/configuration-schema.yml
description: Справочник статусов (коллекция- таксономия)

record:
  id-mode: slug
  file: "{id}.md"
  hierarchy: false

fields:
  code:
    type: awn.string
    title: Код
    required: true
  label:
    type: awn.string
    title: Подпись
    required: true
  emoji:
    type: awn.string
    title: Эмодзи
  color:
    type: awn.color
    title: Цвет
  sort:
    type: awn.integer
    title: Порядок
    default: 0
