version: 1
layer: awn-databases-store

awn_schema:
  record:
    fields:
      awn-title:
        type: awn.string
        title: Название
        required: true
        tab: main
      awn-parent:
        type: awn.string
        title: Родитель
        description: id родительской записи
        tab: main
      awn-status:
        type: awn.field.choice.one
        title: Статус
        enum:
          - open
          - done
        default: open
        tab: main
    tabs:
      main: Основное
