version: 1
kind: collection
id: zagotovki-shablonov
name: Заготовки шаблонов
extends: ../_base/configuration-schema.yml
description: Заготовки шаблонов

record:
  storage: md
  id-mode: numeric
  file: "{id}.md"
  hierarchy: true

fields:
  title:
    type: awn.string
    title: Название
    required: true
  parent:
    type: awn.string
    title: Родитель
    description: id родительской записи
  status:
    type: awn.enum
    title: Статус
    enum: [open, done]
    default: open
