version: 1
layer: awn-databases-store

awn_schema:
  record:
    fields:
      awn-title:
        type: awn.string
        title: Заголовок
        required: true
        tab: main
      awn-hold-ms:
        type: awn.integer
        title: Пауза (мс)
        default: 6500
        tab: main
      awn-status:
        type: awn.field.choice.one
        title: Статус
        enum:
          - active
          - draft
          - inactive
        default: active
        tab: main
    tabs:
      main: Заголовок
