id: awn.record
name: Запись
kind: type
extends: awn.base
description: Запись по умолчанию — элемент в awn-storage/*/main/ (расширяется в configuration.yml темы)
mixins: [awn.mixin.attachments]
fields:
