id: taxonomies/tags
runtime-id: taxonomies.tags
extends: taxonomies/_base
data-root: data/catalog/catalog
manifest: tags.md
storage: awn-storage/tags/main.csv
value-fields:
  - id
  - label
  - color
