version: 1
layer: awn-databases-store

awn_schema:
  frame:
    extends: awn.database.frame.collection
  category:
    extends: awn.database.element.category
  record:
    extends: awn.database.element.record
  record-csv:
    extends: awn.database.element.record-csv
    fields:
      field-1:
        type: awn.field.string
        name: пку
        placement: editor-body
        sort: 10
        title: пку
      field-2:
        type: awn.field.string
        name: пкупку
        placement: editor-body
        sort: 20
        title: пкупку
      field-3:
        type: awn.field.string
        name: пку4
        placement: editor-body
        sort: 30
        title: пку4
  sidecar:
    extends: awn.annotation.sidecar
