version: 1
layer: awn-database-store

awn_schema:
  record:
    extends: awn.data.element.default
    fields:
      awn-title:
        type: awn.string
        title: Название
      awn-path:
        type: awn.string
        title: Путь workspace
        required: true
      awn-environment:
        type: awn.field.choice.one
        title: Окружение
        enum:
          - local
          - staging
          - production
        default: local
      awn-default:
        type: awn.boolean
        title: Агент по умолчанию
        default: false
      awn-orchestrator:
        type: awn.boolean
        title: Оркестратор
        default: false
